// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4NseK9i0hmF02vrTeieETMcq3ndaNQ0',
    appId: '1:886576662240:web:d413558f3284154ab8f285',
    messagingSenderId: '886576662240',
    projectId: 'expense-splitter-c577c',
    authDomain: 'expense-splitter-c577c.firebaseapp.com',
    storageBucket: 'expense-splitter-c577c.firebasestorage.app',
    measurementId: 'G-VZ4KY6RFPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKARLaK2koJbr93S1pkzhc4A4imTS_AWA',
    appId: '1:886576662240:android:3d9befb39055f78bb8f285',
    messagingSenderId: '886576662240',
    projectId: 'expense-splitter-c577c',
    storageBucket: 'expense-splitter-c577c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs8cBQlVog1DPQsk9zkW6VM462QliQ61w',
    appId: '1:886576662240:ios:f5237216533955ddb8f285',
    messagingSenderId: '886576662240',
    projectId: 'expense-splitter-c577c',
    storageBucket: 'expense-splitter-c577c.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs8cBQlVog1DPQsk9zkW6VM462QliQ61w',
    appId: '1:886576662240:ios:f5237216533955ddb8f285',
    messagingSenderId: '886576662240',
    projectId: 'expense-splitter-c577c',
    storageBucket: 'expense-splitter-c577c.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa4NseK9i0hmF02vrTeieETMcq3ndaNQ0',
    appId: '1:886576662240:web:65d966f818fcc701b8f285',
    messagingSenderId: '886576662240',
    projectId: 'expense-splitter-c577c',
    authDomain: 'expense-splitter-c577c.firebaseapp.com',
    storageBucket: 'expense-splitter-c577c.firebasestorage.app',
    measurementId: 'G-3YJWX5PD1E',
  );
}
